name: SBOM

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    steps:
      - name: CycloneDX GoMod Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v1.1.0
        with:
          args: mod -licenses -json -output bom.json
